name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          BASE_PATH: /metronome/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download Pages artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm -rf *
          cp -r github-pages/* ./
          git add .
          git commit -m "Deploy production version from master branch" || echo "No changes to commit"
          git push origin gh-pages
